#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# 이 위저드 전용 값. 커밋하지 않는다 — 세션 파일에는 로그인 토큰이 들어 있다.
# 버전은 대상 레포의 playwright-core 와 맞춘다. 그래야 이미 받아 둔 chromium 을
# 그대로 쓰고 브라우저를 새로 내려받지 않는다.
PW_VERSION="playwright@1.61.0"
DEFAULT_STATE_PATH="$HOME/.config/design-qa/storage-state.json"
ENV_VAR_NAME="PLAYWRIGHT_MCP_STORAGE_STATE"

# add_export FILE NAME VALUE — 셸 프로필에 export 한 줄을 멱등하게 넣는다.
add_export() {
  local file="$1" name="$2" value="$3" tmp
  touch "$file"
  tmp=$(mktemp)
  grep -vE "^export ${name}=" "$file" > "$tmp" || true
  printf 'export %s="%s"\n' "$name" "$value" >> "$tmp"
  mv "$tmp" "$file"
  printf '  %s✓ wrote%s export %s → %s\n' "$GREEN" "$RESET" "$name" "$file"
}

banner "design-qa — Playwright 로그인 세션 만들기"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "준비 확인"
say "이 위저드는 team 존 로그인 세션 파일을 만들고, Playwright MCP가 그 파일을"
say "찾도록 환경변수를 걸어 준다. 브라우저 조작은 사람이 한다."
printf '\n'

if ! command -v npx >/dev/null 2>&1; then
  warn "npx 가 없다. Node.js 를 먼저 설치하고 다시 실행해라."
  exit 1
fi
say "✓ npx 있음"

if [[ -f ".mcp.json" ]] && grep -q '"playwright"' .mcp.json 2>/dev/null; then
  say "✓ .mcp.json 에 playwright 서버 선언 있음"
else
  warn ".mcp.json 에 playwright 선언이 안 보인다. skills 레포 루트에서 실행해라."
  confirm "그래도 계속할까?" || exit 1
fi

printf '\n'
if npx -y "$PW_VERSION" install --dry-run chromium 2>/dev/null | grep -q "Install location"; then
  CHROMIUM_DIR=$(npx -y "$PW_VERSION" install --dry-run chromium 2>/dev/null | grep -m1 "Install location:" | awk '{print $3}')
  if [[ -d "$CHROMIUM_DIR" ]]; then
    say "✓ chromium 있음 — $(basename "$CHROMIUM_DIR")"
  else
    warn "chromium 이 없다. 아래 명령을 먼저 돌려라 (사내망에서 stall 나면 재시도):"
    note "  npx -y $PW_VERSION install chromium"
    confirm "그래도 계속할까?" || exit 1
  fi
fi
pause "다음 단계로."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "세션 파일 자리 정하기"
say "세션 파일에는 로그인 토큰이 들어간다. 레포 안에 두지 마라."
note "대상 레포의 시각 회귀 하네스가 이미 쓰는 경로가 있으면 그걸 그대로 써라."
note "그러면 파일 하나로 MCP 와 하네스 양쪽이 돈다."
printf '\n'
say "기본값: $DEFAULT_STATE_PATH"
ask STATE_PATH "세션 파일 경로 (Enter 로 기본값):"
STATE_PATH="${STATE_PATH:-$DEFAULT_STATE_PATH}"
mkdir -p "$(dirname "$STATE_PATH")"
say "✓ $STATE_PATH 자리 준비됨"

# git 레포 안이면 무시되는지 확인한다. 이 파일에는 로그인 토큰이 들어간다.
STATE_DIR=$(cd "$(dirname "$STATE_PATH")" && pwd)
if git -C "$STATE_DIR" rev-parse --show-toplevel >/dev/null 2>&1; then
  if git -C "$STATE_DIR" check-ignore -q "$STATE_PATH" 2>/dev/null; then
    say "✓ git 이 무시하는 자리다"
  else
    printf '\n'
    warn "이 경로는 git 레포 안인데 .gitignore 에 없다. 커밋되면 로그인 토큰이 샌다."
    note "레포 루트 .gitignore 에 한 줄 넣어라: $(basename "$STATE_DIR")/"
    confirm "지금 넣었나? 계속할까?" || exit 1
  fi
fi
pause "다음 단계로."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "team 존에 로그인해서 세션 덤프"
say "브라우저 창이 열린다. 거기서 team 존에 로그인해라."
warn "로그인이 끝나면 반드시 창을 닫아라. 창을 닫는 순간 세션이 파일로 저장된다."
printf '\n'
ask ZONE_URL "team 존 URL (로그인 화면이 나오는 주소):"
if [[ -z "$ZONE_URL" ]]; then
  warn "URL 없이는 진행할 수 없다."
  exit 1
fi
printf '\n'
step "창이 열리면 로그인한다."
step "로그인된 화면이 보이는지 눈으로 확인한다."
step "창을 닫는다."
pause "준비되면 Enter — 창이 열린다."
npx -y "$PW_VERSION" open --save-storage="$STATE_PATH" "$ZONE_URL"
chmod 600 "$STATE_PATH" 2>/dev/null || true

if [[ ! -f "$STATE_PATH" ]]; then
  warn "세션 파일이 안 생겼다. 창을 닫지 않고 Ctrl-C 로 끊으면 저장되지 않는다."
  exit 1
fi
COOKIE_COUNT=$(node -e 'const s=require(process.argv[1]);console.log((s.cookies||[]).length)' "$STATE_PATH" 2>/dev/null || echo 0)
say "✓ 세션 파일 저장됨 — 쿠키 ${COOKIE_COUNT}개"
if [[ "$COOKIE_COUNT" -eq 0 ]]; then
  warn "쿠키가 0개다. 로그인이 안 된 채로 창을 닫았을 수 있다."
  confirm "그래도 계속할까?" || exit 1
fi
pause "다음 단계로."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "로그인 벽 뒤 화면 찍어서 눈으로 확인"
say "세션이 진짜 사는지 확인한다. 뷰포트는 390x844 — design-qa 가 쓰는 폭이다."
note "주입이 깨지면 로그인 화면이 찍힌다."
warn "VPN 을 켜 둬라. 앱 셸은 뜨는데 API 만 못 붙으면 'Network Error' 가 찍힌다 —"
note "그건 세션 문제가 아니라 망 문제다. 둘을 헷갈리지 마라."
printf '\n'
ask BEHIND_URL "로그인해야만 보이는 화면의 URL (Enter 로 team 존 URL 재사용):"
BEHIND_URL="${BEHIND_URL:-$ZONE_URL}"
SHOT_PATH="$(dirname "$STATE_PATH")/verify-shot.png"
VERIFY_JS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/verify-shot.mjs"
if [[ ! -f "$VERIFY_JS" ]]; then
  warn "verify-shot.mjs 가 위저드 옆에 없다. 같은 폴더에 두고 다시 실행해라."
  exit 1
fi

# CLI `playwright screenshot` 이 아니라 MCP 로 찍는다. CLI 에는
# --grant-permissions 가 없어서 local-network-access 가 거부되고, 앱이
# 로그인 뒤 화면 대신 "Network Error" 를 그린다.
VERIFY_OK=0
PLAYWRIGHT_MCP_STORAGE_STATE="$STATE_PATH" node "$VERIFY_JS" "$BEHIND_URL" "$SHOT_PATH" || VERIFY_OK=$?
[[ -f "$SHOT_PATH" ]] && open_url "file://$SHOT_PATH"
printf '\n'
if [[ "$VERIFY_OK" -ne 0 ]]; then
  warn "검증 실패 — 위 메시지가 원인을 말한다."
  note "Network Error 면 VPN 을 켜고 이 단계만 다시 돌려라."
  note "로그인 화면이면 3단계(로그인 후 창 닫기)를 다시 돌려라."
  exit 1
fi
if confirm "찍힌 화면이 로그인 뒤 화면이 맞나? (눈으로 확인)"; then
  say "✓ 세션 주입 확인됨"
else
  warn "세션이 안 먹었다. 3단계를 다시 돌려라 (로그인 후 창 닫기)."
  exit 1
fi
pause "다음 단계로."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "환경변수 등록"
say "Playwright MCP 는 이 환경변수에서 세션 파일 경로를 읽는다."
note "경로를 레포에 안 적기 위한 방식이다. 이 레포는 공개다."
printf '\n'
case "${SHELL:-}" in
  *zsh)  PROFILE="$HOME/.zshrc" ;;
  *bash) PROFILE="$HOME/.bashrc" ;;
  *)     PROFILE="$HOME/.profile" ;;
esac
say "셸 프로필: $PROFILE"
if confirm "여기에 export 한 줄을 넣을까?"; then
  add_export "$PROFILE" "$ENV_VAR_NAME" "$STATE_PATH"
else
  SKIPPED+=("$ENV_VAR_NAME 수동 등록: export $ENV_VAR_NAME=\"$STATE_PATH\"")
  warn "직접 넣어라: export $ENV_VAR_NAME=\"$STATE_PATH\""
fi
pause "다음 단계로."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Claude Code 재시작하고 확인"
say "MCP 도구는 세션이 시작할 때만 붙는다. 지금 켜져 있는 세션에는 안 붙는다."
printf '\n'
step "터미널을 새로 열거나 'source $PROFILE' 를 돌린다."
step "그 터미널에서 skills 레포로 가서 Claude Code 를 다시 켠다."
step "'mcp__playwright__' 로 시작하는 도구가 뜨는지 본다."
step "그 세션에서 로그인 벽 뒤 화면을 한 장 찍는다 — 티켓 #12 의 완료 기준이다."
printf '\n'
note "세션은 만료되면 자동 갱신되지 않는다. 로그인 화면이 찍히기 시작하면"
note "이 위저드를 다시 돌려라."
pause "확인했으면 Enter."

finish
note "세션 파일: $STATE_PATH (커밋 금지)"
note "환경변수: $ENV_VAR_NAME"
note "확인용 스크린샷: $SHOT_PATH"
